### ISSUE TITLE
Add help text to prose fields

### ISSUE THREAD

**Issue by octopusinvitro** [theyworkforyou/shineyoureye-sinatra#63]
In the prose config file, it is possible to add a help text to be shown in the mata data form, see <https://github.com/theyworkforyou/shineyoureye-prose/blob/gh-pages/_prose.yml#L58>

```yaml
      - name: "eventdate"
        field:
          label: "Event date"
          element: "text"
          help: "The date of the event"
          value: CURRENT_DATETIME
          type: "datetime"
```

which looks like:

![eventdate](https://cloud.githubusercontent.com/assets/2157089/23080032/3a06714c-f547-11e6-9c7b-b830f3e01774.png)
